license="MIT"

[[mods]]
modId="templatetest"
version="1.0.0"
displayName="Template Test 26.x"
description="Minimal template test for 26.1-26.x loaders."

[[dependencies.templatetest]]
modId="neoforge"
type="required"
versionRange="[26.1.2.22-beta,)"
ordering="NONE"
side="BOTH"

[[dependencies.templatetest]]
modId="minecraft"
type="required"
versionRange="[26.1.2]"
ordering="NONE"
side="BOTH"
