modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
    modId="createliquidfuel"
    version="2.1.1-1.20.1"
    displayName="Create Liquid Fuel"
    authors="Forsteri"
    displayTest="IGNORE_SERVER_VERSION"

description='''"Input liquid into blaze burner with pumps & pipes"'''

[[dependencies.createliquidfuel]]
    modId="forge"
    mandatory=true
    versionRange="[47.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.createliquidfuel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.createliquidfuel]]
    modId="create"
    mandatory=true
    versionRange="[0.5.0.e,)"
    ordering="NONE"
    side="BOTH"