modLoader="javafml"
loaderVersion="[1,)"
license="LicenseRef-All-Rights-Reserved"

[[mods]]
modId="seedprotect"
version="1.0.0"
displayName="Seed Protect"
description="Prevents farmland and planted crops from being trampled by players and mobs."
authors="Itamio"
displayURL="https://modrinth.com/mod/seed-protect"

[[dependencies.seedprotect]]
modId="neoforge"
mandatory=true
versionRange="[20.4,)"
ordering="NONE"
side="SERVER"

[[dependencies.seedprotect]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="SERVER"
