modLoader="javafml"
loaderVersion="[64,)"
license="All Rights Reserved"

[[mods]]
modId="examplemod"
version="1.0.0"
displayName="Example Mod"
authors="YourNameHere"

description='''Example mod description.'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[64,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.1,27)"
    ordering="NONE"
    side="BOTH"
