modLoader="javafml"
loaderVersion="[64,)"
license="LicenseRef-All-Rights-Reserved"

[[mods]]
modId="seedprotect"
version="1.0.0"
displayName="Seed Protect"
description="Prevents farmland and planted crops from being trampled by players and mobs."
authors="Itamio"
displayURL="https://modrinth.com/mod/seed-protect"

[[dependencies.seedprotect]]
modId="forge"
mandatory=true
versionRange="[64,)"
ordering="NONE"
side="SERVER"

[[dependencies.seedprotect]]
modId="minecraft"
mandatory=true
versionRange="[26.1.1,)"
ordering="NONE"
side="SERVER"
