modLoader="javafml"
loaderVersion="*"
license="MIT"
clientSideOnly=true
displayTest="IGNORE_ALL_VERSION"

[[mods]]
modId="togglesprint"
version="1.0.0"
displayName="Toggle Sprint"
authors="Itamio"
description="""Client-side toggle sprint for Forge across Minecraft 1.21.6 through 1.21.11"""

[[dependencies.togglesprint]]
modId="forge"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.togglesprint]]
modId="minecraft"
mandatory=true
versionRange="[1.21.11,1.22)"
ordering="NONE"
side="BOTH"
