#!/usr/bin/env python3
"""Auto-commit and push changes cleanly.

Interactive mode:
   - Shows git status
   - Pulls latest from remote to stay up to date
   - Displays all pending changes
   - Lets the user exclude files/folders by adding them to .gitignore
   - Offers to generate commit message with AI (1 = Manual, 2 = AI, default 2)
   - Commits and pushes

Usage:
    python3 scripts/commit_and_push.py                         # Interactive mode (recommended)
    python3 scripts/commit_and_push.py --files a.py b.py -m "message"
    python3 scripts/commit_and_push.py --dry-run -m "message"
"""

import argparse
import json
import os
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path

# GitHub's file size limit
GITHUB_FILE_SIZE_LIMIT = 100 * 1024 * 1024  # 100 MB

# Directories that should always be gitignored
AUTO_IGNORE_DIRS = {"node_modules", ".gradle", "build", ".idea", ".vscode", "__pycache__"}


def run(cmd: list[str], *, check: bool = True, capture: bool = True, timeout: int = 120) -> subprocess.CompletedProcess:
    result = subprocess.run(cmd, capture_output=capture, text=True, timeout=timeout)
    if check and result.returncode != 0:
        stderr = result.stderr.strip() if result.stderr else ""
        raise SystemExit(f"Command failed: {' '.join(cmd)}\n{stderr}")
    return result


def get_current_branch() -> str:
    result = run(["git", "rev-parse", "--abbrev-ref", "HEAD"])
    return result.stdout.strip()


def get_status() -> str:
    result = run(["git", "status", "--porcelain"])
    return result.stdout.strip()


def get_diff_stat() -> str:
    result = run(["git", "diff", "--cached", "--stat"])
    return result.stdout.strip()


def find_gitignore() -> Path:
    """Find or create .gitignore at the repo root."""
    root = run(["git", "rev-parse", "--show-toplevel"]).stdout.strip()
    return Path(root) / ".gitignore"


def read_gitignore(path: Path) -> list[str]:
    if path.exists():
        return path.read_text(encoding="utf-8").splitlines()
    return []


def write_gitignore(path: Path, lines: list[str]) -> None:
    content = "\n".join(lines)
    if not content.endswith("\n"):
        content += "\n"
    path.write_text(content, encoding="utf-8")


def add_to_gitignore(gitignore_path: Path, entry: str) -> None:
    """Add an entry to .gitignore if not already present."""
    lines = read_gitignore(gitignore_path)
    entry = entry.strip()
    if entry and entry not in lines:
        lines.append(entry)
        write_gitignore(gitignore_path, lines)
        print(f"  Added '{entry}' to .gitignore")
    elif entry in lines:
        print(f"  '{entry}' is already in .gitignore")


GITIGNORE_HEADER = (
    "# Auto-generated by commit_and_push.py \u2014 do not edit manually"
)

# Known patterns to skip during file scanning to avoid huge directories
SKIP_DIR_PATTERNS = (
    "node_modules", ".gradle", "build", ".idea", ".vscode",
    "__pycache__", ".git", "target", "bin", "obj",
)


def _find_nested_git_repos(root: str) -> list[str]:
    """Find nested git repositories using git submodule status and directory scan."""
    repos = []

    # Best: use git submodule status (fast, authoritative)
    submod = run(["git", "submodule", "status"], check=False, capture=True)
    if submod.returncode == 0 and submod.stdout.strip():
        for line in submod.stdout.strip().splitlines():
            parts = line.strip().split()
            if len(parts) >= 2:
                repos.append(parts[1].rstrip("/") + "/")
        return repos

    # Fallback: scan top-level directories only (fast)
    for d in Path(root).iterdir():
        if d.is_dir() and not d.name.startswith("."):
            git_dir = d / ".git"
            if git_dir.exists():
                entry = d.name + "/"
                if entry not in repos:
                    repos.append(entry)
    return repos


def _file_size(path: str) -> int:
    try:
        return Path(path).stat().st_size
    except OSError:
        return 0


def scan_problematic_paths(progress_prefix: str = "") -> dict[str, list[str]]:
    """Scan files that would be committed/pushed for issues.

    Returns a dict with keys:
      - 'large_files': paths exceeding GitHub's 100 MB limit
      - 'nested_repos': paths containing a .git subdirectory
      - 'auto_ignore_dirs': paths matching AUTO_IGNORE_DIRS
    """
    def p(msg: str) -> None:
        if progress_prefix:
            print(f"{progress_prefix}{msg}")

    result: dict[str, list[str]] = {
        "large_files": [],
        "nested_repos": [],
        "auto_ignore_dirs": [],
    }

    p("  Scanning for problematic paths...")

    root = run(["git", "rev-parse", "--show-toplevel"]).stdout.strip()
    root_path = Path(root)

    # --- Step 1: Find nested git repos (fast, directory-level) ---
    p("    Checking for nested git repositories...")
    result["nested_repos"] = _find_nested_git_repos(root)

    # --- Step 2: Check common auto-ignore dirs from git status output ---
    p("    Checking for large/temp directories...")
    status_output = run(["git", "status", "--porcelain"]).stdout.strip()
    seen_ignore_dirs: set[str] = set()
    if status_output:
        for line in status_output.splitlines():
            if not line:
                continue
            fpath = line[3:].strip()
            # Check each path component
            parts = Path(fpath).parts
            for i, part in enumerate(parts):
                if part in AUTO_IGNORE_DIRS:
                    dir_rel = str(Path(*parts[:i + 1]))
                    if dir_rel not in seen_ignore_dirs:
                        seen_ignore_dirs.add(dir_rel)
                        result["auto_ignore_dirs"].append(dir_rel)
                    break

    # --- Step 3: Check file sizes on staged/untracked/modified files ---
    p("    Checking file sizes (may take a moment)...")
    # Collect candidate files from status (staged: XY prefix, untracked: ?? prefix)
    candidates: set[str] = set()
    if status_output:
        for line in status_output.splitlines():
            if not line:
                continue
            status_code = line[:2].strip()
            fpath = line[3:].strip()
            # Skip deleted files
            if status_code == "D":
                continue
            # Only check files that would be pushed
            if status_code in ("M", "A", "??", "MM", "AM", "RM"):
                candidates.add(fpath)
            elif status_code == "R":
                # renamed: old -> new
                if " -> " in fpath:
                    candidates.add(fpath.split(" -> ", 1)[1])

    checked = 0
    large = 0
    for rel in candidates:
        full = root_path / rel
        if full.is_file():
            sz = _file_size(str(full))
            checked += 1
            if sz > GITHUB_FILE_SIZE_LIMIT:
                result["large_files"].append(rel)
                large += 1

    p(f"    Checked {checked} file(s), found {large} over {GITHUB_FILE_SIZE_LIMIT // (1024*1024)}MB limit.")
    if result["nested_repos"]:
        p(f"    Found {len(result['nested_repos'])} nested git repo(s).")
    if result["auto_ignore_dirs"]:
        p(f"    Found {len(result['auto_ignore_dirs'])} auto-ignore director(ies).")

    return result


def auto_ignore_problematic_paths(
    problems: dict[str, list[str]],
    gitignore_path: Path,
    interactive: bool = False,
) -> bool:
    """Add detected problematic paths to .gitignore.

    Returns True if any entries were added.
    """
    entries_to_add: list[str] = []

    for path in problems["nested_repos"]:
        pattern = path + "/"
        if pattern not in entries_to_add:
            entries_to_add.append(pattern)

    for path in problems["auto_ignore_dirs"]:
        pattern = path + "/"
        if pattern not in entries_to_add:
            entries_to_add.append(pattern)

    for path in problems["large_files"]:
        pattern = path
        if pattern not in entries_to_add:
            entries_to_add.append(pattern)

    if not entries_to_add:
        return False

    if interactive:
        print("\n  \u26a0\ufe0f  Detected problematic paths that may cause push failures:")
        for key, items in problems.items():
            if items:
                label = {"large_files": "Files >100MB", "nested_repos": "Nested git repos",
                         "auto_ignore_dirs": "Directories to ignore"}[key]
                for item in items:
                    print(f"    - [{label}] {item}")
        answer = input("\n  Add these to .gitignore and untrack them? (Y/n): ").strip().lower()
        if answer not in ("y", "yes", ""):
            print("  Skipping.")
            return False

    current_lines = read_gitignore(gitignore_path)

    # Strip header lines from current if we're going to re-add them
    filtered = [l for l in current_lines if l != GITIGNORE_HEADER and not l.startswith("# Auto-generated")]

    added = 0
    for entry in entries_to_add:
        if entry not in filtered:
            filtered.append(entry)
            added += 1
            print(f"  Added '{entry}' to .gitignore")

    if added > 0:
        write_gitignore(gitignore_path, [GITIGNORE_HEADER] + filtered)

    # Untrack each path from git index
    for entry in entries_to_add:
        run(["git", "rm", "-r", "--cached", entry.rstrip("/")], check=False, capture=True)

    if added > 0:
        print(f"  Untracked {len(entries_to_add)} path(s) from git index.\n")

    return added > 0


def get_working_diff() -> str:
    """Get the full diff of unstaged changes in tracked files."""
    result = run(["git", "diff"], check=False)
    return result.stdout.strip()


def get_status_text() -> str:
    """Get a human-readable summary of pending changes."""
    result = run(["git", "status", "--short"], check=False)
    return result.stdout.strip()


def call_c05localai(system_prompt: str, user_prompt: str, timeout: int = 60) -> str:
    """Call the local c05localai server to generate a commit message.

    Uses the /chat endpoint with a separate system_prompt field for proper
    conversation structure.
    """
    url = "http://localhost:8129/chat"
    payload = {
        "model": "stepfun-ai/step-3.5-flash",
        "hoster": "nvidia",
        "response_mode": "direct",
        "system_prompt": system_prompt,
        "user_prompt": user_prompt,
        "include_history": False,
    }
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as response:
            response_text = response.read().decode("utf-8")
    except urllib.error.URLError as e:
        raise SystemExit(
            f"  Error: Could not reach c05localai server at {url}.\n"
            f"  Make sure it's running (see C05LocalAi/ for setup).\n"
            f"  Details: {e.reason}"
        )
    except TimeoutError:
        raise SystemExit(
            f"  Error: c05localai server timed out after {timeout}s.\n"
            f"  Try again or enter a commit message manually."
        )

    # Parse the NDJSON (newline-delimited JSON) response from the /chat endpoint.
    # The response consists of newline-delimited JSON objects:
    #   {"status": "start", ...}
    #   {"event": "content", "content": "..."}
    #   {"status": "end", "content": "...", ...}
    full_content = ""
    for line in response_text.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            obj = json.loads(line)
        except json.JSONDecodeError:
            continue
        # Capture content from content events
        if obj.get("event") == "content":
            chunk = obj.get("content", "")
            if chunk:
                full_content += chunk
        # Also capture from the final end event (fallback)
        elif obj.get("status") == "end":
            final_content = obj.get("content", "")
            if final_content and not full_content:
                full_content = final_content
    return full_content.strip()


def generate_ai_commit_message() -> str:
    """Generate a commit message from the AI based on the working diff and status."""
    print("  Generating commit message with AI (c05localai)...")

    # Gather context about changes
    status_summary = get_status_text()
    diff_context = get_working_diff()

    if not diff_context and not status_summary:
        raise SystemExit("  Error: No changes detected to generate a commit message.")

    branch = get_current_branch()

    system_prompt = (
        "You are a helpful assistant that writes concise Git commit messages. "
        "Given the git diff, status summary, and branch name, write a clear commit message. "
        "Follow conventional commit format: type(scope): description. "
        "Use types like feat, fix, refactor, chore, docs, test, style, perf, ci. "
        "Keep the description under 72 characters. Do not add any extra commentary or explanation."
    )

    user_prompt = (
        f"Branch: {branch}\n\n"
        f"Changes summary:\n{status_summary}\n\n"
        f"Diff:\n{diff_context}\n"
    )

    print("  Contacting c05localai (stepfun-ai/step-3.5-flash via NVIDIA)...")
    message = call_c05localai(system_prompt, user_prompt)

    if not message:
        raise SystemExit("  AI returned an empty commit message. Try again or enter one manually.")

    return message


def parse_status_files(status_output: str) -> list[dict]:
    """Parse git status --porcelain output into structured entries."""
    entries = []
    for line in status_output.splitlines():
        if not line:
            continue
        status_code = line[:2]
        filepath = line[3:]
        # Handle renamed files (has -> in path)
        if " -> " in filepath:
            filepath = filepath.split(" -> ", 1)[1]
        entries.append({"status": status_code.strip(), "path": filepath})
    return entries


def display_changes(entries: list[dict]) -> None:
    """Display pending changes in a readable format."""
    if not entries:
        print("  No changes detected.")
        return

    status_map = {
        "M": "modified",
        "A": "added",
        "D": "deleted",
        "R": "renamed",
        "??": "untracked",
        "MM": "modified",
        "AM": "added+modified",
    }

    # Group by directory for readability
    print(f"\n  {'Status':<12} {'Path'}")
    print(f"  {'-' * 10}   {'-' * 50}")
    for entry in entries:
        label = status_map.get(entry["status"], entry["status"])
        print(f"  {label:<12} {entry['path']}")
    print()


def interactive_mode() -> None:
    """Run in interactive mode: show status, allow gitignore, commit, push."""
    print("=" * 60)
    print("  commit_and_push.py — Interactive Mode")
    print("=" * 60)

    # Check we're in a git repo
    run(["git", "rev-parse", "--is-inside-work-tree"])

    branch = get_current_branch()
    print(f"\n  Branch: {branch}")

    # Pull latest to stay up to date
    print("\n  Syncing with remote...")
    pull_result = run(["git", "pull", "--rebase", "origin", branch], check=False)
    if pull_result.returncode != 0:
        # May fail if there are unstaged changes; that's fine, we'll push after commit
        if "unstaged changes" in (pull_result.stderr or ""):
            print("  Skipping pull (unstaged changes present, will rebase after commit).")
        elif "Could not read from remote" in (pull_result.stderr or ""):
            print("  Warning: could not reach remote. Continuing offline.")
        else:
            print(f"  Pull note: {(pull_result.stderr or '').strip()[:200]}")
    else:
        print("  Up to date with remote.")

    # Show current status
    status = get_status()
    if not status:
        print("\n  Working tree is clean. Nothing to commit.")
        sys.exit(0)

    entries = parse_status_files(status)
    print(f"\n  Pending changes ({len(entries)} files):")
    display_changes(entries)

    # Auto-detect problematic paths (large files, nested repos, etc.)
    print("\n  \u26a0\ufe0f  Checking for files that could block the push...")
    gitignore_path = find_gitignore()
    problems = scan_problematic_paths(progress_prefix="  ")
    has_problems = any(v for v in problems.values())
    if has_problems:
        auto_ignore_problematic_paths(problems, gitignore_path, interactive=True)
        # Refresh status after gitignore changes
        status = get_status()
        entries = parse_status_files(status)
        print(f"\n  Updated pending changes ({len(entries)} files):")
        display_changes(entries)

    # Gitignore loop
    while True:
        answer = input("  Add any files/folders to .gitignore? (enter path, or 'n' to skip): ").strip()
        if answer.lower() in ("n", "no", ""):
            break

        add_to_gitignore(gitignore_path, answer)

        # Remove from git tracking if already tracked
        run(["git", "rm", "-r", "--cached", answer], check=False, capture=True)

        # Refresh status
        status = get_status()
        entries = parse_status_files(status)
        print(f"\n  Updated pending changes ({len(entries)} files):")
        display_changes(entries)

    # Refresh final status
    status = get_status()
    if not status:
        print("\n  All changes were gitignored. Nothing to commit.")
        sys.exit(0)

    entries = parse_status_files(status)
    print(f"  Final changes to commit ({len(entries)} files):")
    display_changes(entries)

    # Confirm
    confirm = input("  Proceed with commit? (y/n): ").strip().lower()
    if confirm not in ("y", "yes"):
        print("  Aborted.")
        sys.exit(0)

    # Get commit message — choose manual or AI-generated
    message = None
    print("\n  Commit message method:")
    print("    1) Manual — type your own message")
    print("    2) AI     — auto-generate from git diff (default)")
    method = input("  Choose 1 or 2 [2]: ").strip()

    if method == "1":
        # Manual entry
        message = input("  Commit message: ").strip()
    else:
        # AI-generated (default)
        try:
            message = generate_ai_commit_message()
            print(f"\n  AI-generated message:\n    {message}\n")
            choice = input("  Accept? (y/n, or type to edit): ").strip()
            if choice.lower() not in ("y", "yes", ""):
                message = choice if choice.lower() not in ("n", "no") else None
        except SystemExit:
            print("  Falling back to manual entry...\n")

        if not message:
            message = input("  Commit message: ").strip()

    if not message:
        print("  Error: commit message cannot be empty.")
        sys.exit(1)

    # Stage all remaining changes
    print("\n  Staging all changes...")
    run(["git", "add", "-A"])

    staged = get_diff_stat()
    if not staged:
        print("  Nothing staged to commit.")
        sys.exit(0)

    print(f"\n{staged}\n")

    # Commit
    print(f"  Committing: {message}")
    run(["git", "commit", "-m", message])

    # Push (with rebase if needed)
    print(f"  Pushing to origin/{branch}...")
    push_result = run(["git", "push", "origin", branch], check=False)
    if push_result.returncode != 0:
        # Remote may have advanced; try pull --rebase then push again
        print("  Remote has new commits, rebasing...")
        rebase_result = run(["git", "pull", "--rebase", "origin", branch], check=False)
        if rebase_result.returncode != 0:
            stderr = rebase_result.stderr.strip() if rebase_result.stderr else ""
            raise SystemExit(f"  Rebase failed:\n{stderr}")
        push_result = run(["git", "push", "origin", branch], check=False)
        if push_result.returncode != 0:
            # Try setting upstream
            push_result = run(["git", "push", "--set-upstream", "origin", branch], check=False)
            if push_result.returncode != 0:
                stderr = push_result.stderr.strip() if push_result.stderr else ""
                raise SystemExit(f"  Push failed:\n{stderr}")

    print(f"\n  Done. Committed and pushed to origin/{branch}.")


def agent_mode(args: argparse.Namespace) -> None:
    """Run in agent mode: non-interactive commit and push."""
    message = args.message

    if not message:
        raise SystemExit("Error: commit message is required (use -m).")

    # Check we're in a git repo
    run(["git", "rev-parse", "--is-inside-work-tree"])

    # Check there are changes to commit
    status = get_status()
    if not status:
        print("Nothing to commit - working tree is clean.")
        sys.exit(0)

    # Auto-fix problematic paths before staging
    print("\n  \u2699\ufe0f  Checking for files that could block the push...")
    gitignore_path = find_gitignore()
    problems = scan_problematic_paths(progress_prefix="  ")
    if any(v for v in problems.values()):
        print("  \u2699\ufe0f  Auto-fixing problematic paths...")
        auto_ignore_problematic_paths(problems, gitignore_path, interactive=False)
        # Refresh status
        status = get_status()
        if not status:
            print("All changes were filtered out. Nothing to commit.")
            sys.exit(0)

    # Stage files
    if args.files:
        print(f"Staging specified files: {args.files}")
        run(["git", "add", "--"] + args.files)
    else:
        print("Staging all changes...")
        run(["git", "add", "-A"])

    # Check if anything was staged
    staged = get_diff_stat()
    if not staged:
        print("Nothing staged to commit after add.")
        sys.exit(0)

    print(f"\nStaged changes:\n{staged}\n")

    if args.dry_run:
        print("[DRY RUN] Would commit with message:")
        print(f"  {message}")
        print("\n[DRY RUN] Would push to remote.")
        run(["git", "reset", "HEAD"], check=False)
        sys.exit(0)

    # Commit
    print(f"Committing: {message}")
    run(["git", "commit", "-m", message])

    # Determine remote and branch
    branch = get_current_branch()
    print(f"Pushing branch '{branch}' to origin...")

    # Push (set upstream if needed)
    push_result = run(["git", "push", "origin", branch], check=False)
    if push_result.returncode != 0:
        # Try pull --rebase then push
        rebase_result = run(["git", "pull", "--rebase", "origin", branch], check=False)
        if rebase_result.returncode == 0:
            push_result = run(["git", "push", "origin", branch], check=False)
        if push_result.returncode != 0:
            push_result = run(["git", "push", "--set-upstream", "origin", branch], check=False)
            if push_result.returncode != 0:
                stderr = push_result.stderr.strip() if push_result.stderr else ""
                raise SystemExit(f"Push failed:\n{stderr}")

    print(f"\nDone. Committed and pushed to origin/{branch}.")


def quick_mode() -> None:
    """Run in quick mode: auto-commit and push without asking any questions.

    The commit message is auto-generated from the change summary:
      modified #N files/folders added #N files/Folders deleted <paths>
    """
    print("=" * 60)
    print("  commit_and_push.py \u2014 Quick Mode")
    print("=" * 60)

    # Check we're in a git repo
    run(["git", "rev-parse", "--is-inside-work-tree"])

    branch = get_current_branch()
    print(f"\n  Branch: {branch}")

    # Check there are changes to commit
    status = get_status()
    if not status:
        print("  Working tree is clean. Nothing to commit.")
        sys.exit(0)

    # Parse the status to build the commit message BEFORE staging
    entries = parse_status_files(status)

    # Categorise by status code (porcelain codes)
    added = []
    deleted = []
    modified = []

    for entry in entries:
        code = entry["status"]
        path = entry["path"]
        # Untracked -> added
        if code in ("??", "A ", "AM", "A"):
            added.append(path)
        # Deleted in any work area
        elif "D" in code:
            deleted.append(path)
        # The rest: M, MM, R,  M,  , etc.
        else:
            modified.append(path)

    # Build commit message
    parts = []
    if added:
        parts.append(f"#{len(added)} files/folders added")
    if deleted:
        parts.append(f"#{len(deleted)} files/Folders deleted")
    # List the modified/deleted file paths at the end
    changed_paths = [p for p in modified + deleted]
    if changed_paths:
        parts.append(" ".join(changed_paths))

    message = " ".join(parts).strip()
    if not message:
        message = "Quick commit"

    # Auto-fix problematic paths before staging
    print("\n  \u2699\ufe0f  Checking for files that could block the push...")
    gitignore_path = find_gitignore()
    problems = scan_problematic_paths(progress_prefix="  ")
    if any(v for v in problems.values()):
        print("  \u2699\ufe0f  Auto-fixing problematic paths...")
        auto_ignore_problematic_paths(problems, gitignore_path, interactive=False)
        # Refresh status
        status = get_status()
        if not status:
            print("  All changes were filtered out. Nothing to commit.")
            sys.exit(0)
        entries = parse_status_files(status)

    # Stage all changes
    print("\n  Staging all changes...")
    run(["git", "add", "-A"])

    staged = get_diff_stat()
    if not staged:
        print("  Nothing staged to commit.")
        sys.exit(0)

    print(f"\n{staged}\n")
    print(f"  Committing: {message}")
    run(["git", "commit", "-m", message])

    # Pull then push (rebase if needed)
    print(f"  Syncing with remote...")
    pull_result = run(["git", "pull", "--rebase", "origin", branch], check=False)
    if pull_result.returncode != 0:
        if "Could not read from remote" in (pull_result.stderr or ""):
            print("  Warning: could not reach remote. Continuing offline.")
        elif "unstaged changes" in (pull_result.stderr or ""):
            pass  # Already committed, so this is fine

    print(f"  Pushing to origin/{branch}...")
    push_result = run(["git", "push", "origin", branch], check=False)
    if push_result.returncode != 0:
        # Try pull --rebase then push again
        stderr_lower = (push_result.stderr or "").lower()
        if "rejected" in stderr_lower or "fetch first" in stderr_lower:
            print("  Remote has new commits, rebasing...")
            rebase_result = run(["git", "pull", "--rebase", "origin", branch], check=False)
            if rebase_result.returncode != 0:
                stderr = rebase_result.stderr.strip() if rebase_result.stderr else ""
                raise SystemExit(f"  Rebase failed:\n{stderr}")
            push_result = run(["git", "push", "origin", branch], check=False)
        if push_result.returncode != 0:
            push_result = run(["git", "push", "--set-upstream", "origin", branch], check=False)
            if push_result.returncode != 0:
                stderr = push_result.stderr.strip() if push_result.stderr else ""
                raise SystemExit(f"  Push failed:\n{stderr}")

    print(f"\n  Done. Committed and pushed to origin/{branch}.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Auto-commit and push changes cleanly.")
    parser.add_argument("-m", "--message", default=None,
                        help="Commit message (enables non-interactive agent mode)")
    parser.add_argument("--files", nargs="*", default=None,
                        help="Specific files to stage. If omitted, stages all changes.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would be committed without doing it.")
    parser.add_argument("--quick", action="store_true",
                        help="Quick mode: auto-commit and push without asking any questions.")
    args, _ = parser.parse_known_args()

    if args.message:
        agent_mode(args)
    elif args.quick:
        quick_mode()
    else:
        interactive_mode()


if __name__ == "__main__":
    main()
