#!/usr/bin/env python3
"""
Write a README.md into a decompiled-sources folder.
Called by the decompile-all workflow's "Write folder README" step.

Usage:
    python3 scripts/_write_decompile_readme.py <dest_dir> <version> <loader> <java_count> <slug>
"""
import sys
import datetime

dest, version, loader, java_count, slug = (
    sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5]
)
generated = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

content = f"""# Decompiled Minecraft Sources — {version} / {loader}

Auto-generated by the `decompile-all-minecraft-versions-and-add-missing-to-repository`
GitHub Actions workflow.

| Field        | Value                        |
|--------------|------------------------------|
| MC Version   | {version}                    |
| Loader       | {loader}                     |
| Java files   | {java_count}                 |
| Generated    | {generated}                  |

## Purpose

These sources are committed to the repository so that AI coding agents
(Kiro, Copilot, etc.) and developers can browse Minecraft API signatures
without re-running a decompilation step every time.

## How to use

Browse the `.java` files directly, or search with:

```bash
grep -r "YourClassName" DecompiledMinecraftSourceCode/{slug}/
```

Or use the `ai-source-search` workflow for richer query support with
context lines, full class dumps, and API overview generation.
"""

with open(f"{dest}/README.md", "w") as f:
    f.write(content)

print(f"README written to {dest}/README.md")
