modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="examplemod"
version="1.0.0"
displayName="Example Mod"
authors="ExampleAuthor"
description="Example NeoForge mod."

[[dependencies.examplemod]]
modId="neoforge"
mandatory=true
versionRange="[20.6,)"
ordering="NONE"
side="BOTH"

[[dependencies.examplemod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.6,1.21)"
ordering="NONE"
side="BOTH"
